### ISSUE TITLE
Date picker shows dates in strange format

### ISSUE THREAD

**Issue by turntablez** [OraOpenSource/apex-plugin-from-to-datepicker#4]
Love what this picker does but the dates show in a strange format 
eg. DD/MM/YYYY -  20/10/2015 is showing like this :-
![image](https://cloud.githubusercontent.com/assets/13315178/10610853/864eb684-7741-11e5-88ec-af02b34afcca.png)
I am using apex 5.0.0.00.31. 
my Application date format is set to  DD/MM/YYYY and the time/date format is set to DD/MM/YYYY HH24:MI:SS
Not sure if this is something I am doing wrong or a bug.

Also a request too, could you put the time to this too?
Thanks!

**Comment by martindsouza** [comment]
@turntablez I think this is due to an escaping issue. I think this is due to some escaping that occurs while displaying the value. 

Note to self, look at changing the escaping in `f_render_from_to_datepicker` from `apex_escape.html` to `apex_escape.json`.

**Comment by martindsouza** [comment]
Issue is resolved in 2.1.0. I have added a ticket for the time request (won't be in the 2.1.0 release).

**Comment by turntablez** [comment]
Hi,

This works! 
Its a great addition to a annual leave application I have wrote.

Thanks

Alex.

Alex Turnbull
Junior Software Developer
APEX Evangelists Ltd
website: http://apex-evangelists.com

Registered Company Address: 16 Gateland Drive, Leeds, West Yorkshire, United Kingdom. LS17 8HU
Company number 06277247. Registered in England & Wales.

Disclaimer: This e-mail contains proprietary information some or all of which may be legally privileged. It is for the intended recipient only. If an addressing or transmission error has misdirected this e-mail, please notify the author by replying to this e-mail and then permanently delete the message from your computer. If you are not the intended recipient you must not use, disclose, distribute, copy, print or rely on the e-mail.

While attachments are virus checked, Apex Evangelists Ltd does not accept any liability in respect of a virus which is not detected.
