### ISSUE TITLE
Cannot change 2nd date once a date has been picked

### ISSUE THREAD

**Issue by jeffreykemp** [OraOpenSource/apex-plugin-from-to-datepicker#5]
Case #1
1. Enter a date for the 1st item, e.g. 10 Sep.
2. Enter a date for the 2nd item, e.g. 11 Sep.
3. Open the date picker on the 2nd item.

Expected: can select any date on or after 10 Sep.
Actual: can only select dates between 10 Sep and 11 Sep.
Workaround: clear the date from the item first

Case #2
1. Enter a date for the 1st item, e.g. 10 Sep.
2. Enter a date for the 2nd item, e.g. 11 Sep.
3. Change the 1st date to an invalid date, e.g. 12 Sep.
4. Attempt to change the 2nd date.

Expected: can select any date on or after 12 Sep.
Actual: cannot select any date at all, cannot navigate months.

Case #3
1. Enter a date for the 1st item, e.g. 10 Sep.
2. Enter a date for the 2nd item, e.g. 11 Sep.
3. Attempt to change the 1st date.

Expected: can select any date not later than 11 Sep.
Actual: can select any date.

I suspect these issues are related.

**Comment by vincentmorneau** [comment]
+1

It was working fine in the pre-5.0 version: https://apex.oracle.com/pls/apex/f?p=45587:700:0

**Comment by martindsouza** [comment]
@jeffreykemp @vincentmorneau This is not a bug, rather a configuration option. You probably have the following setting for the `TO_DATE` item:

![image](https://cloud.githubusercontent.com/assets/2925726/11764762/4aa290dc-a0fa-11e5-8de5-72cc4da77954.png)

This does raise a good point, that the plugin should catch this issue as it can be very hard to debug. As such I will update the plugin to show an `alert` message on run time to let developers know right away:

![image](https://cloud.githubusercontent.com/assets/2925726/11764765/74c9c61e-a0fa-11e5-8a9f-72cce8339c57.png)

As well, when the application is run in debug mode it will be obvious to developer and provide reference back to this issue:

![image](https://cloud.githubusercontent.com/assets/2925726/11764774/b2c09ce0-a0fa-11e5-8dea-924a1f02cf30.png)

**Comment by martindsouza** [comment]
Update: As they're other possible mis-configurations I have moved all the configurations into the plugin render function. As such these will now be PL/SQL errors that show up when the page is run if the item configuration is invalid.
